---
title: "overlap gene regions"
author: "Joe McGirr"
date: "7/30/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(tidyverse)
library(reticulate)
library(reshape2)
library(plyranges)
#BiocManager::install("visFuns.R")


# color-blind friendly 
# Wong, B. Points of view: Color blindness. Nat Methods (2011).
bla <- "#000000"
blu <- "#0072b2"
grb <- "#56b4e9"
lir <- "#cc79a7"
gre <- "#009e73"
red <- "#d55e00"
org <- "#e69f00"
yel <- "#f0e442"
gry<-  '#BBBBBB'

```

## Fst outliers

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width= 10, fig.height= 7}

gff <- read.delim("C:/Users/jmcgirr/Documents/Whitehead_Lab/ph/annotations/Clupea_harengus.Ch_v2.0.2.100.gff3",header = FALSE, sep = "\t",comment.char = '#')
head(gff)
colnames(gff) <- c("seqnames","source","type","start","end","score","strand","phase","attributes")
genes <- gff[gff$type=="gene",]
genes <- genes %>% separate(attributes, c("at1","at2"), remove = FALSE,sep = "Name=") %>% separate(at2, c("gene_name","at3"), extra = "drop",sep = ";")
genes <- select(genes, -at1,-at3)
g <- genes[genes$strand == "\\.",]
head(genes)
genes <- droplevels(genes)

genes <- genes %>% as_granges()
fsts <- list.files(path="C:/Users/jmcgirr/Documents/Whitehead_Lab/ph/angsd/SFS/fst/sliding_window/", full.names=T)


fst <- read.delim("C:/Users/jmcgirr/Documents/Whitehead_Lab/ph/angsd/SFS/fst/sliding_window/fst_pbs_50kb_win_10kb_step_TB17_PWS17_SS17.txt")
fst <- fst %>% mutate(chr = gsub("[A-z]", "", chr))
fst$start <- fst$midPos-9999
fst$end <- fst$midPos+9999
colnames(fst)[colnames(fst) == 'chr'] <- 'seqnames'

quantile(fst$Fst01,.999)
fst_outlier <- fst[fst$Fst01 >= quantile(fst$Fst01,.99)[[1]],]


chr6 <- fst_outlier[fst_outlier$seqnames == 6,]

chr6 <- chr6 %>% as_granges()
chr6 <- join_overlap_intersect(chr6, genes) %>% as.data.frame()
head(chr6)
chr6
write.table(as.data.frame(unique(chr6$gene_name)), "C:/Users/jmcgirr/Desktop/genes_delete.txt", quote= FALSE, row.names = FALSE)

```

