---
title: "popvae"
author: "Joe McGirr"
date: "10/29/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(data.table)
library(plyranges)
library(ggplot2)
library(tidyverse)
library(reticulate)
library(reshape2)
library(seqinr)

# color-blind friendly 
# Wong, B. Points of view: Color blindness. Nat Methods (2011).
bla <- "#000000"
blu <- "#0072b2"
grb <- "#56b4e9"
lir <- "#cc79a7"
gre <- "#009e73"
red <- "#d55e00"
org <- "#e69f00"
yel <- "#f0e442"
gry<-  '#BBBBBB'

```

## All populations and years
Separation between Togiak Bay and all other populations dominates  
Consistent with high Fst (range: 0.28 - 0.35)
```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width= 10, fig.height= 7}

pop_info <- read.table("C:/Users/jmcgirr/Documents/Whitehead_Lab/ph/familiarize/EVOS_MasterSheet_JoeMcGirr_April2020.txt", header = TRUE, stringsAsFactors = FALSE, sep = "\t")
aligned <- read.table("C:/Users/jmcgirr/Documents/Whitehead_Lab/ph/familiarize/aligned_samples.txt", header = TRUE, stringsAsFactors = FALSE, sep = "\t")
pop_info <- pop_info[pop_info$Sample %in% aligned$sample,]
vcf_samples <- read.table("C:/Users/jmcgirr/Documents/Whitehead_Lab/ph/plink/plates_1_through_5_rm.txt", header = FALSE, stringsAsFactors = FALSE, sep = "\t")
names(vcf_samples)[names(vcf_samples)=="V1"] <- "Sample"
vcf_sample_info <- inner_join(vcf_samples,pop_info, by = "Sample")
vcf_sample_info$sampleID <- vcf_sample_info$Sample

#load data
pd <- fread("C:/Users/jmcgirr/Documents/Whitehead_Lab/ph/popvae/ph_filtered_snps_minDP600_maxDP2000_maf0.05_minQ20_minMQ30_maxmiss0.5_outliers_rm_random_thin_latent_coords.txt",header=T)
names(pd)[1:2] <- c("LD1","LD2")
#merge tables
dd <- merge(pd,vcf_sample_info,by="sampleID")
dd <- dd %>% separate(Population.Year, into = c("pop", "year"), sep = "(?<=[A-Za-z])(?=[0-9])")
ggplot(data = dd)+
  geom_point(data = dd, aes(x = LD1, y = LD2, fill = pop, color = pop, shape = year), size = 3)+
  scale_fill_manual(values=c(grb,org,red,yel,blu,lir), guide=FALSE)+
  scale_color_manual(name = "population", values=c(grb,org,red,yel,blu,lir))+
  scale_shape_manual(name = "year", values=c(21,22,23,24,25))+
  xlab("LD1")+
  ylab("LD2")+
  theme_bw()

```

## Remove Togiak Bay
Separation between California and all other populations dominates

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width= 10, fig.height= 7}

pd <- fread("C:/Users/jmcgirr/Documents/Whitehead_Lab/ph/popvae/ph_filtered_snps_minDP600_maxDP2000_maf0.05_minQ20_minMQ30_maxmiss0.5_outliers_rm_noTB_random_thin_latent_coords.txt",header=T)
names(pd)[1:2] <- c("LD1","LD2")
dd <- merge(pd,vcf_sample_info,by="sampleID")
dd <- dd %>% separate(Population.Year, into = c("pop", "year"), sep = "(?<=[A-Za-z])(?=[0-9])")
ggplot(data = dd)+
  geom_point(data = dd, aes(x = LD1, y = LD2, fill = pop, color = pop, shape = year), size = 3)+
  scale_fill_manual(values=c(grb,org,red,yel,lir), guide=FALSE)+
  scale_color_manual(name = "population", values=c(grb,org,red,yel,lir))+
  scale_shape_manual(name = "year", values=c(21,22,23,24,25))+
  xlab("LD1")+
  ylab("LD2")+
  theme_bw()
```

## PWS

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width= 10, fig.height= 7}

# pd <- fread("C:/Users/jmcgirr/Documents/Whitehead_Lab/ph/popvae/NEPac17_random_thin_latent_coords.txt",header=T)
# names(pd)[1:2] <- c("LD1","LD2")
# dd <- merge(pd,vcf_sample_info,by="sampleID")
# dd <- dd %>% separate(Population.Year, into = c("pop", "year"), sep = "(?<=[A-Za-z])(?=[0-9])")
# ggplot(data = dd)+
#   geom_point(data = dd, aes(x = LD1, y = LD2, fill = pop, color = pop, shape = year), size = 3)+
#   scale_fill_manual(values=c(grb,red,yel,lir), guide=FALSE)+
#   scale_color_manual(name = "population", values=c(grb,red,yel,lir))+
#   scale_shape_manual(name = "year", values=c(21,22,23,24,25))+
#   xlab("LD1")+
#   ylab("LD2")+
#   theme_bw()

pd <- fread("C:/Users/jmcgirr/Documents/Whitehead_Lab/ph/popvae/PWS_random_thin_latent_coords.txt",header=T)
names(pd)[1:2] <- c("LD1","LD2")
dd <- merge(pd,vcf_sample_info,by="sampleID")
dd <- dd %>% separate(Population.Year, into = c("pop", "year"), sep = "(?<=[A-Za-z])(?=[0-9])")
ggplot(data = dd)+
  geom_point(data = dd, aes(x = LD1, y = LD2, color = pop, shape = year), size = 3)+
  #scale_fill_manual(values=c(red), guide=FALSE)+
  scale_color_manual(name = "population", values=c(red))+
  scale_shape_manual(name = "year", values=c(21,22,23,24,25))+
  xlab("LD1")+
  ylab("LD2")+
  theme_bw()
```

## TB

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width= 10, fig.height= 7}

pd <- fread("C:/Users/jmcgirr/Documents/Whitehead_Lab/ph/popvae/TB_random_thin_latent_coords.txt",header=T)
names(pd)[1:2] <- c("LD1","LD2")
dd <- merge(pd,vcf_sample_info,by="sampleID")
dd <- dd %>% separate(Population.Year, into = c("pop", "year"), sep = "(?<=[A-Za-z])(?=[0-9])")
ggplot(data = dd)+
  geom_point(data = dd, aes(x = LD1, y = LD2, color = pop, shape = year), size = 3)+
  #scale_fill_manual(values=c(red), guide=FALSE)+
  scale_color_manual(name = "population", values=c(blu))+
  scale_shape_manual(name = "year", values=c(21,22,23,24,25))+
  xlab("LD1")+
  ylab("LD2")+
  theme_bw()
```

## SS

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width= 10, fig.height= 7}


pd <- fread("C:/Users/jmcgirr/Documents/Whitehead_Lab/ph/popvae/SS_random_thin_latent_coords.txt",header=T)
names(pd)[1:2] <- c("LD1","LD2")
dd <- merge(pd,vcf_sample_info,by="sampleID")
dd <- dd %>% separate(Population.Year, into = c("pop", "year"), sep = "(?<=[A-Za-z])(?=[0-9])")
ggplot(data = dd)+
  geom_point(data = dd, aes(x = LD1, y = LD2, color = pop, shape = year), size = 3)+
  #scale_fill_manual(values=c(red), guide=FALSE)+
  scale_color_manual(name = "population", values=c(bla))+
  scale_shape_manual(name = "year", values=c(22,23,24,25))+
  xlab("LD1")+
  ylab("LD2")+
  theme_bw()

```