---
title: "Pacific Herring LD and pi"
author: "Joe McGirr"
date: '`r Sys.Date()`'
output:
  html_document:
    code_folding: hide
    collapsed: no
    df_print: paged
    number_sections: yes
    theme: paper
    toc: yes
    toc_depth: 5
    toc_float: yes
  html_notebook:
    toc: yes
    toc_depth: 5
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(tidyverse)
library(reticulate)
library(reshape2)
library(plyranges)
library(seqinr)
library(data.table)
#BiocManager::install("visFuns.R")


# color-blind friendly 
# Wong, B. Points of view: Color blindness. Nat Methods (2011).
bla <- "#000000"
blu <- "#0072b2"
grb <- "#56b4e9"
lir <- "#cc79a7"
gre <- "#009e73"
red <- "#d55e00"
org <- "#e69f00"
yel <- "#f0e442"
gry<-  '#BBBBBB'

```


# Ne estimates from Watterson's theta
```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width= 10, fig.height= 7}

# Rough Ne estimate using waterson's theta

# http://evomics.org/learning/population-and-speciation-genomics/2018-population-and-speciation-genomics/angsd-activity-sfs-fst-pbs/

pop_names = c("PWS91","PWS96","PWS07","PWS17","TB91","TB96","TB06","TB17","SS96","SS06","SS17","BC17","WA17","CA17")
pop <- "PWS07"
ne_s <- c()
for (pop in pop_names){
x<-scan(paste("C:/Users/jmcgirr/Documents/Whitehead_Lab/ph/sfs/downsample_41/folded/",pop,"_minQ20_minMQ30_folded.sfs", sep = ""))

nSites<-sum(x)   #Number of sites where we have data
nSeg<-sum(x[c(-1)])    #Number of segregating sites
an <- function(n) sum(1/1:(n-1))
thetaW <- nSeg/an(length(x[c(-1)])/2) # Wattersons Theta
#print(pop)
#print("effective population size")
ne <- thetaW / 2.0e-9 / nSites / 4 # effective population size
#print(ne)
ne_s <- c(ne_s, ne)
}

barplot(ne_s, names.arg = pop_names, ylab = expression('N '[e]), col = c(red,red,red,red,blu,blu,blu,blu,yel,yel,yel,grb,lir,org),cex.names=0.7)

```


## LD Decay 
### No big differences in LD decay between populations. Drops to background levels between 200bp (Atlantic Herring LD drops off around 100bp).

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width= 10, fig.height= 7}

pop_names = c("PWS91","PWS96","PWS07","PWS17")
pop_line <- c(4,3,2,1)
pop <- "PWS91"
i <- 1
ld <- read.table(paste("C:/Users/jmcgirr/Documents/Whitehead_Lab/ph/plink/pops/population_",pop_names[i],"_ph_filtered_snps_minDP600_maxDP2000_minQ20_minMQ30_NS0.5_maf0.05_indep_pairwise_100_10_0.8.ld",sep = ''), header = TRUE, stringsAsFactors = FALSE)
ld$distance <- ld$BP_B-ld$BP_A

plot(ld$distance, ld$R2, col = "white", xlim = c(0,1000), xlab = "distance (bp)" ,ylab = "r2")
smooth_ld <-smooth.spline(ld$distance, ld$R2, spar = .15)
lines(smooth_ld, lwd = 2,lty = pop_line[i], col = red)

for (i in c(2:length(pop_names))){
ld <- read.table(paste("C:/Users/jmcgirr/Documents/Whitehead_Lab/ph/plink/pops/population_",pop_names[i],"_ph_filtered_snps_minDP600_maxDP2000_minQ20_minMQ30_NS0.5_maf0.05_indep_pairwise_100_10_0.8.ld",sep = ''), header = TRUE, stringsAsFactors = FALSE)
ld$distance <- ld$BP_B-ld$BP_A

#ld <- ld[ld$CHR_A == "1" & ld$CHR_B == "1" ,]

smooth_ld <-smooth.spline(ld$distance, ld$R2, spar = .15)
lines(smooth_ld, lwd = 2,lty = pop_line[i], col = red)
}


pop_names = c("TB91","TB96","TB06","TB17")
pop_line <- c(4,3,2,1)
pop <- "TB91"

i <- 1
ld <- read.table(paste("C:/Users/jmcgirr/Documents/Whitehead_Lab/ph/plink/pops/population_",pop_names[i],"_ph_filtered_snps_minDP600_maxDP2000_minQ20_minMQ30_NS0.5_maf0.05_indep_pairwise_100_10_0.8.ld",sep = ''), header = TRUE, stringsAsFactors = FALSE)
ld$distance <- ld$BP_B-ld$BP_A

plot(ld$distance, ld$R2, col = "white", xlim = c(0,1000), xlab = "distance (bp)" ,ylab = "r2")
smooth_ld <-smooth.spline(ld$distance, ld$R2, spar = .15)
lines(smooth_ld, lwd = 2,lty = pop_line[i], col = blu)

for (i in c(2:length(pop_names))){
ld <- read.table(paste("C:/Users/jmcgirr/Documents/Whitehead_Lab/ph/plink/pops/population_",pop_names[i],"_ph_filtered_snps_minDP600_maxDP2000_minQ20_minMQ30_NS0.5_maf0.05_indep_pairwise_100_10_0.8.ld",sep = ''), header = TRUE, stringsAsFactors = FALSE)
ld$distance <- ld$BP_B-ld$BP_A

#ld <- ld[ld$CHR_A == "1" & ld$CHR_B == "1" ,]

smooth_ld <-smooth.spline(ld$distance, ld$R2, spar = .15)
lines(smooth_ld, lwd = 2,lty = pop_line[i], col = blu)
}


```


```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width= 10, fig.height= 7, eval = FALSE}

pop_names = c("PWS91","PWS96","PWS07","PWS17")
pop_line <- c(4,3,2,1)
pop <- "PWS91"

ld <- read.table(paste("C:/Users/jmcgirr/Documents/Whitehead_Lab/ph/angsd/ngsLD/chr1_thin20k_",pop,"_60k_pairs_ld.txt",sep = ''), header = FALSE, stringsAsFactors = FALSE)
colnames(ld) <- c("snpA","snpB","distance","r_squared_pearson","D_EM","D_prime_EM","r_squared_EM")
ld[mapply(is.infinite, ld)] <- NA
ld <- na.omit(ld)

#png("C:/Users/jmcgirr/Documents/Whitehead_Lab/ph/figs/population_structure/LD_PWS.png", height = 6, width = 7, units = 'in', res = 600)


plot(ld$distance, ld$r_squared_EM,xlim = c(0,1000), col = "white",ylim = c(0.1,0.6), xlab = "distance (bp)", ylab = expression(paste("r"^" 2")), main = "PWS")
legend(835, 0.6, legend=c("91", "96","06/07","17"),col="black", lty=c(4,3,2,1), cex=1,bty = "n" )

for (i in c(1:length(pop_names))){

# plot LD decay with smooth spline
ld <- read.table(paste("C:/Users/jmcgirr/Documents/Whitehead_Lab/ph/angsd/ngsLD/chr1_thin20k_",pop_names[i],"_60k_pairs_ld.txt",sep = ''), header = FALSE, stringsAsFactors = FALSE)
colnames(ld) <- c("snpA","snpB","distance","r_squared_pearson","D_EM","D_prime_EM","r_squared_EM")
ld[mapply(is.infinite, ld)] <- NA
ld <- na.omit(ld)

smooth_ld <-   smooth.spline(ld$distance, ld$r_squared_EM, spar = .15)
lines(smooth_ld, lwd = 2,lty = pop_line[i], col = red)

}

#dev.off()

# TB

pop_names = c("TB91","TB96","TB06","TB17")
pop_line <- c(4,3,2,1)
pop <- "PWS91"

plot(ld$distance, ld$r_squared_EM,xlim = c(0,1000), col = "white",ylim = c(0.1,0.6), xlab = "distance (bp)", ylab = expression(paste("r"^" 2")), main = "TB")
legend(835, 0.6, legend=c("91", "96","06/07","17"),col="black", lty=c(4,3,2,1), cex=1,bty = "n" )


for (i in c(1:length(pop_names))){

# plot LD decay with smooth spline
ld <- read.table(paste("C:/Users/jmcgirr/Documents/Whitehead_Lab/ph/angsd/ngsLD/chr1_thin20k_",pop_names[i],"_60k_pairs_ld.txt",sep = ''), header = FALSE, stringsAsFactors = FALSE)
colnames(ld) <- c("snpA","snpB","distance","r_squared_pearson","D_EM","D_prime_EM","r_squared_EM")
ld[mapply(is.infinite, ld)] <- NA
ld <- na.omit(ld)

smooth_ld <-   smooth.spline(ld$distance, ld$r_squared_EM, spar = .15)
lines(smooth_ld, lwd = 2,lty = pop_line[i], col = blu)

}

# SS
pop_names = c("SS96","SS06","SS17")
pop_line <- c(3,2,1)
pop <- "PWS91"

#png("C:/Users/jmcgirr/Documents/Whitehead_Lab/ph/figs/population_structure/LD_SS.png", height = 6, width = 7, units = 'in', res = 600)

plot(ld$distance, ld$r_squared_EM,xlim = c(0,1000), col = "white",ylim = c(0.1,0.6), xlab = "distance (bp)", ylab = expression(paste("r"^" 2")), main = "SS")
legend(835, 0.6, legend=c("96","06/07","17"),col="black", lty=c(3,2,1), cex=1,bty = "n" )


for (i in c(1:length(pop_names))){

# plot LD decay with smooth spline
ld <- read.table(paste("C:/Users/jmcgirr/Documents/Whitehead_Lab/ph/angsd/ngsLD/chr1_thin20k_",pop_names[i],"_60k_pairs_ld.txt",sep = ''), header = FALSE, stringsAsFactors = FALSE)
colnames(ld) <- c("snpA","snpB","distance","r_squared_pearson","D_EM","D_prime_EM","r_squared_EM")
ld[mapply(is.infinite, ld)] <- NA
ld <- na.omit(ld)

smooth_ld <-   smooth.spline(ld$distance, ld$r_squared_EM, spar = .15)
lines(smooth_ld, lwd = 2,lty = pop_line[i], col = yel)

}

#dev.off()

# southern 2017s
pop_names = c("BC17","WA17","CA17")
pop_cols = c(grb,lir,org)
pop_line <- c(3,2,1)
pop <- "PWS91"

plot(ld$distance, ld$r_squared_EM,xlim = c(0,1000), col = "white",ylim = c(0.1,0.6), xlab = "distance (bp)", ylab = expression(paste("r"^" 2")), main = "BC WA CA")
legend(835, 0.6, legend=c("BC17","WA17","CA17"),col=c(grb,lir,org), lty=c(1,1,1), cex=1,bty = "n" )


for (i in c(1:length(pop_names))){

# plot LD decay with smooth spline
ld <- read.table(paste("C:/Users/jmcgirr/Documents/Whitehead_Lab/ph/angsd/ngsLD/chr1_thin20k_",pop_names[i],"_60k_pairs_ld.txt",sep = ''), header = FALSE, stringsAsFactors = FALSE)
colnames(ld) <- c("snpA","snpB","distance","r_squared_pearson","D_EM","D_prime_EM","r_squared_EM")
ld[mapply(is.infinite, ld)] <- NA
ld <- na.omit(ld)

smooth_ld <-   smooth.spline(ld$distance, ld$r_squared_EM, spar = .15)
lines(smooth_ld, lwd = 2,lty = 1, col = pop_cols[i])

}

## Stairway plot 
#https://onlinelibrary.wiley.com/doi/full/10.1111/eva.12985
#https://github.com/popgenmethods/smcpp#quick-start-guide

```






