---
title: "Pi_TajD_Fst_Dxy"
author: "Joe McGirr"
date: "1/7/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# SFS
```{r}
# using SFS from angsd -dosaf -bam

pop_names <- c("BC17","CA17","PWS07","PWS17","PWS91","PWS96","SS06","SS17","SS96","TB06","TB17","TB91","TB96","WA17")

#pop_name <- "BC17"

for (pop_name in pop_names){
sfs <- read.table(paste("C:/Users/jmcgirr/Documents/Whitehead_Lab/ph/angsd/downsample_41/sfs/folded/chunks/",pop_name,"_minQ20_minMQ30_folded.sfs",sep = ""), header = FALSE, stringsAsFactors = FALSE)
sfs
sfs <- as.vector(colSums(sfs))
barplot(sfs[-c(1,length(sfs))]) #plot variable sites 
#write.table(t(sfs),paste("C:/Users/jmcgirr/Documents/Whitehead_Lab/ph/angsd/downsample_41/sfs/folded/",pop_name,"_minQ20_minMQ30_folded.sfs",sep = ""), quote = FALSE, row.names = FALSE, col.names = FALSE)
}

# https://github.com/ANGSD/angsd/issues/97

# using SFS from angsd -dosaf -vcf-pl


```


## Pi and Tajima's D

```{r}

# thetas <-read.delim('C:/Users/jmcgirr/Documents/Whitehead_Lab/ph/angsd/SFS/thetas/population_BC17_ph_filtered_snps_minD# P600_maxDP2000_maf0.05_minQ20_minMQ30_maxmiss0.5_theta.thetas10kbWindow.gz.pestPG')
# #pi = tP/nsites
# #https://doi.org/10.1186/s12862-018-1209-y
# thetas$pi <- thetas$tP/thetas$nSites 
# chr1 <- thetas %>% filter(Chr == "chr1")
# range(thetas$Tajima)
# range(na.omit(thetas$pi))
# 
# 
# plot(chr1$WinCenter, chr1$Tajima)
# plot(chr1$WinCenter, chr1$pi)

pop_names <- c("BC17","CA17","PWS07","PWS17","PWS91","PWS96","SS06","SS17","SS96","TB06","TB17","TB91","TB96","WA17")
pop_names <- c("CA17","PWS07","PWS17","PWS91","PWS96","SS06","SS17","SS96","TB06","TB17","TB91","TB96","WA17")

pop <- "BC17"
#thetas <-read.delim(paste('C:/Users/jmcgirr/Documents/Whitehead_Lab/ph/angsd/SFS/thetas/50kb/population_',pop,'_ph_filtered_snps_minDP600_maxDP2000_maf0.05_minQ20_minMQ30_maxmiss0.5_theta.thetas50kbWindow.gz.pestPG',sep = ""))
thetas <-read.delim(paste('C:/Users/jmcgirr/Documents/Whitehead_Lab/ph/angsd/downsample_41/thetas/folded/',pop,'_minQ20_minMQ30_50kb_win_10kb_step.pestPG',sep = ""))
thetas <- thetas[c("Tajima")]
names(thetas)[names(thetas)=="Tajima"] <- pop

for (pop in pop_names){

thetas1 <-read.delim(paste('C:/Users/jmcgirr/Documents/Whitehead_Lab/ph/angsd/downsample_41/thetas/folded/',pop,'_minQ20_minMQ30_50kb_win_10kb_step.pestPG',sep = ""))
thetas1[c("Chr","WinCenter","Tajima")]
thetas$Tajima <- thetas1$Tajima
names(thetas)[names(thetas)=="Tajima"] <- pop 
  
}

my_cols <- c(grb,org,red,red,red,red,yel,yel,yel,blu,blu,blu,blu,lir)
theta_test <- thetas %>% 
      gather(key="MesureType", value="Val")
p1 <- thetas %>% 
      gather(key="MesureType", value="Val") %>%
      ggplot( aes(x=reorder(MesureType,Val, FUN = mean), y=Val, fill=MesureType)) +
      geom_violin() + xlab("\npopulation/year") + ylab("Tajima's D\n")+
      scale_fill_manual(name = "Population",values=my_cols,guide=FALSE)+
      #stat_summary(fun=mean, geom="line")+
      theme_minimal()
      #geom_jitter(height = 0, width = 0.1, alpha = 0.1)

#png("C:/Users/jmcgirr/Documents/Whitehead_Lab/ph/figs/population_structure/taj_d.png", height = 5, width = 7, units = 'in', res = 600)

p1

#dev.off()

#https://github.com/ANGSD/angsd/issues/329#issuecomment-681005380
# pi

pop <- "BC17"
thetas <-read.delim(paste('C:/Users/jmcgirr/Documents/Whitehead_Lab/ph/angsd/downsample_41/thetas/folded/',pop,'_minQ20_minMQ30_50kb_win_10kb_step.pestPG',sep = ""))
#thetas$pi<- (thetas$tP*thetas$nSites)/10000
thetas$pi<- thetas$tP/thetas$nSites
#thetas$pi<- thetas$tP/50000
thetas <- thetas[c("pi")]
names(thetas)[names(thetas)=="pi"] <- pop

for (pop in pop_names){

thetas1 <-read.delim(paste('C:/Users/jmcgirr/Documents/Whitehead_Lab/ph/angsd/downsample_41/thetas/folded/',pop,'_minQ20_minMQ30_50kb_win_10kb_step.pestPG',sep = ""))
#thetas1$pi<- (thetas1$tP*thetas1$nSites)/10000
thetas1$pi<- thetas1$tP/thetas1$nSites
thetas1[c("Chr","WinCenter","pi")]
thetas$pi <- thetas1$pi
names(thetas)[names(thetas)=="pi"] <- pop 
  
}

my_cols <- c(grb,org,red,red,red,red,yel,yel,yel,blu,blu,blu,blu,lir)
thetas <- na.omit(thetas)
p1 <- thetas %>% 
      gather(key="MesureType", value="Val") %>%
      ggplot( aes(x=reorder(MesureType,Val, FUN = median), y=Val, fill=MesureType)) +
      geom_violin() + xlab("\npopulation/year") + ylab(expression(pi))+
      scale_fill_manual(name = "Population",values=my_cols,guide=FALSE)+
      theme_minimal()
      #geom_jitter(height = 0, width = 0.1, alpha = 0.1)

#png("C:/Users/jmcgirr/Documents/Whitehead_Lab/ph/figs/population_structure/pi_angsd.png", height = 5, width = 7, units = 'in', res = 600)

p1

#dev.off()

### vcftools just to get a sense with hard calls since angsd values are stupid high
#pi_50kb_win_BC17_ph_filtered_snps_minDP600_maxDP2000_maf0.05_minQ20_minMQ30_maxmiss0.5_plates_1_5_rm.txt.windowed
pop <- "BC17"
thetas <-read.delim(paste('C:/Users/jmcgirr/Documents/Whitehead_Lab/ph/angsd/SFS/thetas/vcftools/pi_50kb_win_',pop,'_ph_filtered_snps_minDP600_maxDP2000_maf0.05_minQ20_minMQ30_maxmiss0.5_plates_1_5_rm.txt.windowed.pi',sep = ""))
#thetas$pi<- (thetas$tP*thetas$nSites)/10000
#thetas$pi<- thetas$tP/thetas$nSites
#thetas$pi<- thetas$tP/50000
thetas <- head(thetas, 14500)
thetas <- thetas[c("PI")]
names(thetas)[names(thetas)=="PI"] <- pop

for (pop in pop_names){

thetas1 <-read.delim(paste('C:/Users/jmcgirr/Documents/Whitehead_Lab/ph/angsd/SFS/thetas/vcftools/pi_50kb_win_',pop,'_ph_filtered_snps_minDP600_maxDP2000_maf0.05_minQ20_minMQ30_maxmiss0.5_plates_1_5_rm.txt.windowed.pi',sep = ""))
#thetas1$pi<- (thetas1$tP*thetas1$nSites)/10000
#thetas1$pi<- thetas1$tP/thetas1$nSites
#thetas1[c("Chr","WinCenter","pi")]
thetas1 <- head(thetas1, nrow(thetas))
thetas$pi <- thetas1$PI
names(thetas)[names(thetas)=="pi"] <- pop 
  
}

my_cols <- c(grb,org,red,red,red,red,yel,yel,yel,blu,blu,blu,blu,lir)
p1 <- thetas %>% 
      gather(key="MesureType", value="Val") %>%
      ggplot( aes(x=reorder(MesureType,Val, FUN = median), y=Val, fill=MesureType)) +
      geom_violin() + xlab("\npopulation/year") + ylab("pi\n")+
      scale_fill_manual(name = "Population",values=my_cols,guide=FALSE)+
      theme_minimal()
      #geom_jitter(height = 0, width = 0.1, alpha = 0.1)

#png("C:/Users/jmcgirr/Documents/Whitehead_Lab/ph/figs/population_structure/pi_vcftools.png", height = 5, width = 7, units = 'in', res = 600)

p1

#dev.off()



```

## Fst

```{r}

pop_names = c("PWS91","PWS96","PWS07","PWS17","TB91","TB96","TB06","TB17","SS96","SS06","SS17","BC17","WA17","CA17")

pop0 <- "TB17"
pop1 <- "PWS17"
pop2 <- "SS17"

fsts <- list.files(path="C:/Users/jmcgirr/Documents/Whitehead_Lab/ph/angsd/SFS/fst/sliding_window/", full.names=T)
#fsts <- fsts[1]

for (f in fsts){  

pops <- strsplit(f, "_")
pops <- c(pops[[1]][9], pops[[1]][10],gsub("\\.txt","",pops[[1]][11]))

fst <-read.delim(paste("C:/Users/jmcgirr/Documents/Whitehead_Lab/ph/angsd/SFS/fst/sliding_window/fst_pbs_50kb_win_10kb_step_",pops[1],"_",pops[2],"_",pops[3],".txt", sep = ""))
#head(fst)
fst <- fst %>% mutate(chr = as.numeric(gsub("chr", "", chr)))
fst$chr_num <- factor(fst$chr, levels = c(1:26))

# Fst
p <- ggplot(fst, aes(x = midPos, y = Fst01)) + 
     geom_point(size = 1, color = gry,alpha = 0.4, shape = 1)+
     theme_minimal()+
     theme(axis.text.x=element_blank())+
     ylab("Fst\n")+ xlab("")+ 
     ggtitle(paste(pops[1],"vs. ", pops[2]))+
     geom_smooth(method = "loess", se = FALSE, span = 1/10, color = blu)+
     facet_wrap(~chr_num, ncol = 9)
print(p)

p <- ggplot(fst, aes(x = midPos, y = Fst02)) + 
     geom_point(size = 1, color = gry,alpha = 0.4, shape = 1)+
     theme_minimal()+
     theme(axis.text.x=element_blank())+
     ylab("Fst\n")+ xlab("")+ 
     ggtitle(paste(pops[1],"vs. ", pops[3]))+
     geom_smooth(method = "loess", se = FALSE, span = 1/10, color = blu)+
     facet_wrap(~chr_num, ncol = 9)
print(p)

p <- ggplot(fst, aes(x = midPos, y = Fst12)) + 
     geom_point(size = 1, color = gry,alpha = 0.4, shape = 1)+
     theme_minimal()+
     theme(axis.text.x=element_blank())+
     ylab("Fst\n")+ xlab("")+ 
     ggtitle(paste(pops[2],"vs. ", pops[3]))+
     geom_smooth(method = "loess", se = FALSE, span = 1/10, color = blu)+
     facet_wrap(~chr_num, ncol = 9)
print(p)

#PBS
p <- ggplot(fst, aes(x = midPos, y = PBS0)) + 
     geom_point(size = 1, color = gry,alpha = 0.4, shape = 1)+
     theme_minimal()+
     theme(axis.text.x=element_blank())+
     ylab("PBS\n")+ xlab("")+ 
     ggtitle(paste(pops[1]))+
     geom_smooth(method = "loess", se = FALSE, span = 1/10, color = red)+
     facet_wrap(~chr_num, ncol = 9)
print(p)

p <- ggplot(fst, aes(x = midPos, y = PBS1)) + 
     geom_point(size = 1, color = gry,alpha = 0.4, shape = 1)+
     theme_minimal()+
     theme(axis.text.x=element_blank())+
     ylab("PBS\n")+ xlab("")+ 
     ggtitle(paste(pops[2]))+
     geom_smooth(method = "loess", se = FALSE, span = 1/10, color = red)+
     facet_wrap(~chr_num, ncol = 9)
print(p)

p <- ggplot(fst, aes(x = midPos, y = PBS2)) + 
     geom_point(size = 1, color = gry,alpha = 0.4, shape = 1)+
     theme_minimal()+
     theme(axis.text.x=element_blank())+
     ylab("PBS\n")+ xlab("")+ 
     ggtitle(paste(pops[3]))+
     geom_smooth(method = "loess", se = FALSE, span = 1/10, color = red)+
     facet_wrap(~chr_num, ncol = 9)
print(p)

}

#dxy




# chr1 <- fst %>% filter(chr == "chr1")
# 
# plot(chr1$midPos, chr1$Fst01)
# plot(chr1$midPos, chr1$Fst02)
# plot(chr1$midPos, chr1$Fst12)
# 
# plot(chr1$midPos, chr1$PBS0)
# plot(chr1$midPos, chr1$PBS1)
# plot(chr1$midPos, chr1$PBS2)

```



```{r, echo = FALSE,results='hide'}
## Site Frequency Spectrum
# s<-scan('C:/Users/jmcgirr/Documents/Whitehead_Lab/ph/angsd/SFS/thetas/population_BC17_ph_filtered_snps_minDP600_maxDP20# 00_maf0.05_minQ20_maxmiss0.5.sfs')
# s<-s[-c(1,length(s))]
# s<-s/sum(s)
# barplot(s,names=1:length(s),main='SFS')
```


## Dxy

```{r, results= "hide", eval=FALSE}

mafs_dir <- "C:/Users/jmcgirr/Documents/Whitehead_Lab/ph/angsd/SFS/dxy/mafs/"
comps <- c("TB_PWS","TB_SS","TB_BC","TB_WA","TB_CA",
           "PWS_SS","PWS_BC","PWS_WA","PWS_CA",
           "SS_BC","SS_WA","SS_CA",
           "BC_WA","BC_CA",
           "WA_CA")
yr <- "17"
comp <- "TB_PWS"

for (comp in comps){

popA <- paste(strsplit(comp,"_")[[1]][1],yr, sep = "")
popB <- paste(strsplit(comp,"_")[[1]][2],yr, sep = "")

allfreqA <- read.table(paste(mafs_dir,popA,"_vcf.mafs", sep = ""),sep='\t',row.names=NULL, header=T)
allfreqB <- read.table(paste(mafs_dir,popB,"_vcf.mafs", sep = ""),sep='\t',row.names=NULL, header=T)

### Manipulating the table and print dxy table
allfreq <- merge(allfreqA, allfreqB, by=c("chromo","position"))
allfreq <- allfreq[order(allfreq$chromo, allfreq$position),]
# -> Actual dxy calculation
allfreq <- transform(allfreq, dxy=(knownEM.x*(1-knownEM.y))+(knownEM.y*(1-knownEM.x)))

#head(allfreq)

rol_win <- winScan(x = allfreq, 
                   groups = "chromo", 
                   position = "position", 
                   values = c("dxy"), 
                   win_size = 50000,
                   win_step = 10000,
                   funs = c("sum"))
rol_win$dxy <- rol_win$dxy_sum/50000

#write.table(rol_win, file=paste("C:/Users/jmcgirr/Documents/Whitehead_Lab/ph/angsd/SFS/dxy/windows/",popA,"_",popB,"_Dxy_50kb_win_10kb_step.txt",sep = ""),quote=FALSE, row.names=FALSE, sep='\t')
print('Created Dxy_persite.txt')

### Print global dxy
print(paste0(popA, popB,' Global dxy is: ',mean(rol_win$dxy)))
  
}


dxys <- list.files(path="C:/Users/jmcgirr/Documents/Whitehead_Lab/ph/angsd/SFS/dxy/windows/", full.names=T)
#d <- dxys[1]

for (d in dxys){  

pops <- strsplit(d, "/")
pops <- strsplit(pops[[1]][11], "_")

pops <- c(pops[[1]][1], pops[[1]][2])
dxy <- read.delim(paste("C:/Users/jmcgirr/Documents/Whitehead_Lab/ph/angsd/SFS/dxy/windows/",pops[1],"_",pops[2],"_Dxy_50kb_win_10kb_step.txt", sep = ""))
#head(fst)
dxy <- dxy %>% mutate(chromo = as.numeric(gsub("chr", "", chromo)))
dxy$chr_num <- factor(dxy$chr, levels = c(1:26))


p <- ggplot(dxy, aes(x = win_mid, y = dxy)) + 
     geom_point(size = 1, color = gry,alpha = 0.4, shape = 1)+
     theme_minimal()+
     theme(axis.text.x=element_blank())+
     ylab("Dxy\n")+ xlab("")+ 
     ggtitle(paste(pops[1],"vs. ", pops[2]))+
     geom_smooth(method = "loess", se = FALSE, span = 1/10, color = org)+
     facet_wrap(~chr_num, ncol = 9)
print(p)

}




fst_vec <- c(0,tbxpw,tbxss,tbxbc,tbxwa,tbxca,
             tbxpw,0,pwxss,pwxbc,pwxwa,pwxca,
             tbxss,pwxss,0,ssxbc,ssxwa,ssxca,
             tbxbc,pwxbc,ssxbc,0,bcxwa,bcxca,
             tbxwa,pwxwa,ssxwa,bcxwa,0,waxca,
             tbxca,pwxca,ssxca,bcxca,waxca,0)

fst_mat = matrix(fst_vec, nrow = 6, ncol = 6)
colnames(fst_mat) <- c("TB17","PWS17","SS17","BC17","WA17","CA17")
rownames(fst_mat) <- c("TB17","PWS17","SS17","BC17","WA17","CA17")
print(fst_mat)

```

