---
title: "PCA_row_labels"
output:
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(tidyverse)
library(reticulate)
library(ggpubr)
library(sf)
library(gridExtra)
library(grid)
#BiocManager::install("visFuns.R")


# color-blind friendly 
# Wong, B. Points of view: Color blindness. Nat Methods (2011).
bla <- "#000000"
blu <- "#0072b2"
grb <- "#56b4e9"
lir <- "#cc79a7"
gre <- "#009e73"
red <- "#d55e00"
org <- "#e69f00"
yel <- "#f0e442"
gry<-  '#BBBBBB'

```


### For each plate, view individuals in sets of 8 corresponding to their row on the plate.  


```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width= 10, fig.height= 7}
pop_info <- read.table("C:/Users/jmcgirr/Documents/Whitehead_Lab/ph/familiarize/EVOS_MasterSheet_JoeMcGirr_April2020_plate_rows.txt", header = TRUE, stringsAsFactors = FALSE, sep = "\t")
aligned <- read.table("C:/Users/jmcgirr/Documents/Whitehead_Lab/ph/familiarize/aligned_samples.txt", header = TRUE, stringsAsFactors = FALSE, sep = "\t")
pop_info <- pop_info[pop_info$Sample %in% aligned$sample,]
vcf_samples <- read.table("C:/Users/jmcgirr/Documents/Whitehead_Lab/ph/familiarize/samples_in_vcf.txt", header = FALSE, stringsAsFactors = FALSE, sep = "\t")
names(vcf_samples)[names(vcf_samples)=="V1"] <- "Sample"
vcf_sample_info <- inner_join(vcf_samples,pop_info, by = "Sample")

chr <- "1"
C <- as.matrix(read.table(paste("C:/Users/jmcgirr/Documents/Whitehead_Lab/ph/angsd/PCAngsd/chr",chr,"_ph_filtered_snps_minDP600_maxDP2000_maf0.05_minQ20_minMQ30_maxmiss0.5.cov", sep = "")))
e <- eigen(C)
pca <-data.frame(Sample=vcf_sample_info$Sample, 
                 pop=vcf_sample_info$Population.Year,
                 plate=vcf_sample_info$Sequence.Plate,
                 plate_row=vcf_sample_info$plate_row,
                 PC1=e$vectors[,1],PC2=e$vectors[,2],
                 PC3=e$vectors[,3],PC4=e$vectors[,4],
                 PC5=e$vectors[,5],PC6=e$vectors[,6],
                 PC7=e$vectors[,7],PC8=e$vectors[,8],
                 PC9=e$vectors[,9],PC10=e$vectors[,10],
                 stringsAsFactors=FALSE)

prop_explained <- c()
for (s in e$values[1:10]) {
  #print(s / sum(e$values))
  prop_explained <- c(prop_explained,round(((s / sum(e$values))*100),2))
}

pca <- pca %>% separate(pop, into = c("pop", "year"), sep = "(?<=[A-Za-z])(?=[0-9])")
pca1 <- pca



for (plate_num in c(1:20))
#for (plate_num in c(4))
{
plate_num_str <- as.character(plate_num)
  for (plate_row in c(1:8))
  {
  plate_row_str <- as.character(plate_row)
  p1 <- ggplot(data = pca1)+
    geom_point(data = pca1, aes(x = PC1, y = PC2, fill = pop, color = pop, shape = year), size = 3)+
    scale_fill_manual(values=c(grb,org,red,yel,blu,lir), guide=FALSE)+
    scale_color_manual(name = "population", values=c(grb,org,red,yel,blu,lir))+
    scale_shape_manual(name = "year", values=c(21,22,23,24,25))+
    xlab(paste("PC 1: ", prop_explained[1],"%\n",sep = ""))+
    ylab(paste("PC 2: ", prop_explained[2],"%\n",sep = ""))+
    theme_bw()+
    geom_text(data=subset(pca1, plate_row == plate_row_str & plate == plate_num_str),aes(x = PC1, y = PC2,label = Sample))+
    ggtitle(paste("plate ",plate_num_str,"\nrow ",plate_row_str,sep = ""))
    print(p1)
}
}


#out_rm <- vcf_sample_info %>% filter(Sequence.Plate != 1 & 
#                                     Sequence.Plate != 2 &
#                                     Sequence.Plate != 3 &
#                                     Sequence.Plate != 4 &
#                                     Sequence.Plate != 5) %>%
#           separate(Population.Year, into = c("pop", "year"), sep = "(?<=[A-Za-z])(?=[0-9])")%>% 
#            filter(pop != "TB")
#count(out_rm, vars = Population.Year)

#write.table(as.data.frame(out_rm$Sample),"C:/Users/jmcgirr/Documents/Whitehead_Lab/ph/plink/plates_1_through_5_rm_no_TB.txt",quote = FALSE,row.names = FALSE)

                                     
```

###"bad" indicates obviously wrong grouping. "strange" indicates that one or two samples in the row showed odd grouping. 

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width= 10, fig.height= 7}
bads <- read.table("C:/Users/jmcgirr/Documents/Whitehead_Lab/ph/familiarize/bad_plates_by_row.txt", header = TRUE, stringsAsFactors = FALSE, sep = "\t")
#head(t(bads))
grid.arrange(tableGrob(bads,theme=ttheme_default(base_size = 10),rows = NULL))

```
